/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "+";
  }
}
/* JavaCC - OriginalChecksum=4699da1c96515c12ab9e2596a5731720 (do not edit this line) */
