/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTAnd extends SimpleNode {
  static int count = 0;
  int labelId;

  public ASTAnd(int id) {
    super(id);
    this.labelId = count;
    count++;
  }

  public ASTAnd(Parser p, int id) {
    super(p, id);
    this.labelId = count;
    count++;
  }

  public int getLabelId() {
    return this.labelId;
  }

  public String toString() {
    return "&&";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=895a039285b4da1a01d54e9b6eba4ff5 (do not edit this line) */
