/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTClass extends SimpleNode {
  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(Parser p, int id) {
    super(p, id);
  }

  public String getExtends() {
    for (Node n : this.children)
      if (n instanceof ASTExtends)
        return ((SimpleNode) n).getVal().toString();

    return "";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9d770e7631cd414c8137bfa2aab90325 (do not edit this line) */
