/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTClass extends SimpleNode {
  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef3e2359a6d66a6e9122c41f65ba7cac (do not edit this line) */
