/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0481b5adc25ef6764b8a948abd79c44a (do not edit this line) */
