/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Parser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8ca5417e73294596a51cf53f894ab467 (do not edit this line) */
