/* Generated By:JJTree: Do not edit this line. ASTExtends.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTExtends extends SimpleNode {
  public ASTExtends(int id) {
    super(id);
  }

  public ASTExtends(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc4ec47da194799e6c1166b26d11c16d (do not edit this line) */
