/* Generated By:JJTree: Do not edit this line. ASTElse.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTElse extends SimpleNode {
  public ASTElse(int id) {
    super(id);
  }

  public ASTElse(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30819862f34d591eb4f053693a6cd143 (do not edit this line) */
