/* Generated By:JJTree: Do not edit this line. ASTExprStmt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTExprStmt extends SimpleNode {
  public ASTExprStmt(int id) {
    super(id);
  }

  public ASTExprStmt(Parser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=41a599b6cf87f5030d414aa6666d1196 (do not edit this line) */
