/* Generated By:JJTree: Do not edit this line. ASTExprSuffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTExprSuffix extends SimpleNode {
  protected String kind = null;

  public ASTExprSuffix(int id) {
    super(id);
  }

  public ASTExprSuffix(Parser p, int id) {
    super(p, id);
  }
  
  public String toString() {
    if (children == null) 
      return super.toString();

    return this.kind + " " + this.val;
  }
}
/* JavaCC - OriginalChecksum=01c0afa9f27089268a03b0630c455d89 (do not edit this line) */
