/* Generated By:JJTree: Do not edit this line. ASTFalse.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTFalse extends SimpleNode {
  public ASTFalse(int id) {
    super(id);
  }

  public ASTFalse(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bdae87df10a13c1507b5ebb16456431 (do not edit this line) */
