/* Generated By:JJTree: Do not edit this line. ASTIfCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTIfCondition extends SimpleNode {
  public ASTIfCondition(int id) {
    super(id);
  }

  public ASTIfCondition(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=18704d47114a474fff9137915eca5dba (do not edit this line) */
