/* Generated By:JJTree: Do not edit this line. ASTIfCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTIfCondition extends SimpleNode {
  public ASTIfCondition(int id) {
    super(id);
  }

  public ASTIfCondition(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ace643aa0682d212897712eaecbe99a (do not edit this line) */
