/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "int" + " " + this.val;
  }
}
/* JavaCC - OriginalChecksum=032ce87fc9865f69865d55915d7c3c1a (do not edit this line) */
