/* Generated By:JJTree: Do not edit this line. ASTLessThan.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTLessThan extends SimpleNode {
  static int count = 0;
  int labelId;

  public ASTLessThan(int id) {
    super(id);
    this.labelId = count;
    count++;
  }

  public ASTLessThan(Parser p, int id) {
    super(p, id);
    this.labelId = count;
    count++;
  }

  public int getLabelId() {
    return this.labelId;
  }

  public String toString() {
    return "<";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bdf17da7b5f8bd4c26cda2383d47ea5f (do not edit this line) */
