/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    if (children == null)
      return super.toString();

    return super.toString() + "[" + children[0].toString() + "]";
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix));
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=66aacc100383372485b24e6cb3f2ead8 (do not edit this line) */
