/* Generated By:JJTree: Do not edit this line. ASTMain.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMain extends SimpleNode {
  public ASTMain(int id) {
    super(id);
  }

  public ASTMain(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0727def28e75f59e9d8b75a88e9d8f5 (do not edit this line) */
