/* Generated By:JJTree: Do not edit this line. ASTMethodParams.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodParams extends SimpleNode {
  public ASTMethodParams(int id) {
    super(id);
  }

  public ASTMethodParams(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3fb2b9343b0347aa8913494919d82b99 (do not edit this line) */
