/* Generated By:JJTree: Do not edit this line. ASTMethodParam.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodParam extends SimpleNode {
  public ASTMethodParam(int id) {
    super(id);
  }

  public ASTMethodParam(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0b5bf2dba8d4e47bf85551c642cee3cc (do not edit this line) */
