/* Generated By:JJTree: Do not edit this line. ASTMethodCallArgs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodCallArgs extends SimpleNode {
  public ASTMethodCallArgs(int id) {
    super(id);
  }

  public ASTMethodCallArgs(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=65702ac622e0dc901c15fbd86c773e88 (do not edit this line) */
