/* Generated By:JJTree: Do not edit this line. ASTMethodCallArgs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodCallArgs extends SimpleNode {
  public ASTMethodCallArgs(int id) {
    super(id);
  }

  public ASTMethodCallArgs(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=67b2216858c4a45020cdaa9a0bdba5f4 (do not edit this line) */
