/* Generated By:JJTree: Do not edit this line. ASTMul.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMul extends SimpleNode {
  public ASTMul(int id) {
    super(id);
  }

  public ASTMul(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "*";
  }
}
/* JavaCC - OriginalChecksum=63ef49b2b4cced76f16ea088d24f6aec (do not edit this line) */
