/* Generated By:JJTree: Do not edit this line. ASTMethodArgs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodArgs extends SimpleNode {
  public ASTMethodArgs(int id) {
    super(id);
  }

  public ASTMethodArgs(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f4322de625b7000475f34e6d337eb87b (do not edit this line) */
