/* Generated By:JJTree: Do not edit this line. ASTMethodParams.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodParams extends SimpleNode {
  public ASTMethodParams(int id) {
    super(id);
  }

  public ASTMethodParams(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7a8d84cde54c061a92eb1224c8667a8 (do not edit this line) */
