/* Generated By:JJTree: Do not edit this line. ASTMethodArg.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodArg extends SimpleNode {
  public ASTMethodArg(int id) {
    super(id);
  }

  public ASTMethodArg(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f0b59a10ba00cb63bd5c2c004ec83f14 (do not edit this line) */
