/* Generated By:JJTree: Do not edit this line. ASTMethodParam.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodParam extends SimpleNode {
  public ASTMethodParam(int id) {
    super(id);
  }

  public ASTMethodParam(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be2998ee4282adcb2f4c9388c28357f5 (do not edit this line) */
