/* Generated By:JJTree: Do not edit this line. ASTMethodCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMethodCall extends SimpleNode {
  public ASTMethodCall(int id) {
    super(id);
  }

  public ASTMethodCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3cbfd064845d74254de03c353cb0a50 (do not edit this line) */
