/* Generated By:JJTree: Do not edit this line. ASTNew.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTNew extends SimpleNode {
  public ASTNew(int id) {
    super(id);
  }

  public ASTNew(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2b2e28dbfd12702ac7bfe956b148586 (do not edit this line) */
