/* Generated By:JJTree: Do not edit this line. ASTParam.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTParam extends SimpleNode {
  public ASTParam(int id) {
    super(id);
  }

  public ASTParam(Parser p, int id) {
    super(p, id);
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + " " + children[0].toString());
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46c3142ce25c1eaf705d9ab2fe382707 (do not edit this line) */
