/* Generated By:JJTree: Do not edit this line. ASTParam.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTParam extends SimpleNode {
  public ASTParam(int id) {
    super(id);
  }

  public ASTParam(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46c3142ce25c1eaf705d9ab2fe382707 (do not edit this line) */
