/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(Parser p, int id) {
    super(p, id);
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + " " + children[0].toString());
  }
}
/* JavaCC - OriginalChecksum=8a561855f273d959c6fd11b5e9925e8b (do not edit this line) */
