/* Generated By:JJTree: Do not edit this line. ASTRhs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package AST;

public class ASTRhs extends SimpleNode {
  public ASTRhs(int id) { super(id); }

  public ASTRhs(Parser p, int id) { super(p, id); }

  public String toString() {
    /* if (children.length == 1)
      return super.toString() + " " + children[0].toString(); */

    return super.toString();
  }

  public void dump(String prefix) {
    /* if (children.length == 1) {
      System.out.println(toString(prefix));
      return;
    } */

    super.dump(prefix);
  }
}
/* JavaCC - OriginalChecksum=294886a99568be47f4534765d2089a14 (do not edit this
 * line) */
