/* Generated By:JJTree: Do not edit this line. ASTTrue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=39e9f890c156bbfe32bac28dee013952 (do not edit this line) */
