/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTVariable extends SimpleNode {
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9adb520c109ebbd9499d35e742d56a0a (do not edit this line) */
