/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a620a5943238c6955de3bb49778ab71 (do not edit this line) */
