/* Generated By:JJTree: Do not edit this line. ASTWhileCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTWhileCondition extends SimpleNode {
  public ASTWhileCondition(int id) {
    super(id);
  }

  public ASTWhileCondition(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b17d16f75567a70c2a384a96e26d842d (do not edit this line) */
