/* Generated By:JJTree: Do not edit this line. ASTWhileCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTWhileCondition extends SimpleNode {
  public ASTWhileCondition(int id) {
    super(id);
  }

  public ASTWhileCondition(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e0b252ac398f4a9d514cf366d11af896 (do not edit this line) */
