/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 6.0_1 */
package AST;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTClass node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTExtends node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTMethod node, Object data);
  public Object visit(ASTReturn node, Object data);
  public Object visit(ASTReturnStmt node, Object data);
  public Object visit(ASTMethodParams node, Object data);
  public Object visit(ASTMethodParam node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTLhs node, Object data);
  public Object visit(ASTRhs node, Object data);
  public Object visit(ASTIf node, Object data);
  public Object visit(ASTIfCondition node, Object data);
  public Object visit(ASTElse node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTWhileCondition node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTLessThan node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMul node, Object data);
  public Object visit(ASTDiv node, Object data);
  public Object visit(ASTExprSuffix node, Object data);
  public Object visit(ASTMethodCallArgs node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTThis node, Object data);
  public Object visit(ASTNew node, Object data);
}
/* JavaCC - OriginalChecksum=6156bf4fce241c46f7f377cefdf07c2f (do not edit this line) */
