/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package AST;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCLASS = 1;
  public int JJTNAME = 2;
  public int JJTVOID = 3;
  public int JJTEXTENDS = 4;
  public int JJTMAIN = 5;
  public int JJTMETHOD = 6;
  public int JJTRETURN = 7;
  public int JJTPARAMS = 8;
  public int JJTPARAM = 9;
  public int JJTTYPE = 10;
  public int JJTVARIABLE = 11;
  public int JJTASSIGN = 12;
  public int JJTLHS = 13;
  public int JJTRHS = 14;
  public int JJTEXPRSTMT = 15;
  public int JJTIF = 16;
  public int JJTIFCONDITION = 17;
  public int JJTELSE = 18;
  public int JJTWHILE = 19;
  public int JJTWHILECONDITION = 20;
  public int JJTAND = 21;
  public int JJTLESSTHAN = 22;
  public int JJTADD = 23;
  public int JJTSUB = 24;
  public int JJTMUL = 25;
  public int JJTDIV = 26;
  public int JJTMETHODCALL = 27;
  public int JJTINTEGER = 28;
  public int JJTTRUE = 29;
  public int JJTFALSE = 30;
  public int JJTID = 31;
  public int JJTTHIS = 32;
  public int JJTNEW = 33;


  public String[] jjtNodeName = {
    "Start",
    "Class",
    "Name",
    "void",
    "Extends",
    "Main",
    "Method",
    "Return",
    "Params",
    "Param",
    "Type",
    "Variable",
    "Assign",
    "Lhs",
    "Rhs",
    "ExprStmt",
    "If",
    "IfCondition",
    "Else",
    "While",
    "WhileCondition",
    "And",
    "LessThan",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "MethodCall",
    "Integer",
    "True",
    "False",
    "Id",
    "This",
    "New",
  };
}
/* JavaCC - OriginalChecksum=89774fa5ac3b3807695a40953abc391d (do not edit this line) */
