/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package AST;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTNAME = 2;
  public int JJTVOID = 3;
  public int JJTEXTENDS = 4;
  public int JJTMAIN = 5;
  public int JJTMETHOD = 6;
  public int JJTRETURN = 7;
  public int JJTRETURNSTMT = 8;
  public int JJTMETHODPARAMS = 9;
  public int JJTMETHODPARAM = 10;
  public int JJTTYPE = 11;
  public int JJTVARIABLE = 12;
  public int JJTASSIGN = 13;
  public int JJTLHS = 14;
  public int JJTRHS = 15;
  public int JJTIF = 16;
  public int JJTIFCONDITION = 17;
  public int JJTELSE = 18;
  public int JJTWHILE = 19;
  public int JJTWHILECONDITION = 20;
  public int JJTAND = 21;
  public int JJTLESSTHAN = 22;
  public int JJTADD = 23;
  public int JJTSUB = 24;
  public int JJTMUL = 25;
  public int JJTDIV = 26;
  public int JJTEXPRSUFFIX = 27;
  public int JJTMETHODCALLARGS = 28;
  public int JJTINTEGER = 29;
  public int JJTTRUE = 30;
  public int JJTFALSE = 31;
  public int JJTID = 32;
  public int JJTTHIS = 33;
  public int JJTNEW = 34;


  public String[] jjtNodeName = {
    "Program",
    "Class",
    "Name",
    "void",
    "Extends",
    "Main",
    "Method",
    "Return",
    "ReturnStmt",
    "MethodParams",
    "MethodParam",
    "Type",
    "Variable",
    "Assign",
    "Lhs",
    "Rhs",
    "If",
    "IfCondition",
    "Else",
    "While",
    "WhileCondition",
    "And",
    "LessThan",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "ExprSuffix",
    "MethodCallArgs",
    "Integer",
    "True",
    "False",
    "Id",
    "This",
    "New",
  };
}
/* JavaCC - OriginalChecksum=dc112b805290dd1d8f8cc757c9d58bac (do not edit this line) */
